packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  nx: true

minimumReleaseAge: 1440

catalog:
  '@storybook/addon-docs': 10.2.13
  '@storybook/addon-svelte-csf': 5.0.11
  '@storybook/svelte': 10.2.13
  '@storybook/sveltekit': 10.2.13
  storybook: 10.2.13
  '@sveltejs/adapter-static': 3.0.10
  '@sveltejs/kit': 2.57.1
  '@sveltejs/vite-plugin-svelte': 6.2.4
  '@tailwindcss/vite': 4.1.18
  svelte: 5.55.5
  svelte-check: 4.6.0
  tailwindcss: 4.1.18
  typescript: 6.0.3
  vite: 7.3.5
  vitest: 4.1.8
