export const folderMetadataColorNames = [
  'coral',
  'peach',
  'butter',
  'sage',
  'mint',
  'lime',
  'sky',
  'periwinkle',
  'lavender',
  'rose',
  'teal',
  'slate'
] as const;

export const folderMetadataIconNames = [
  'bookmark',
  'home',
  'vault',
  'book',
  'activity',
  'people',
  'star',
  'user',
  'stop',
  'history',
  'refresh',
  'fullscreen',
  'panel',
  'collapse',
  'expand-rail',
  'dots',
  'settings',
  'plus',
  'search',
  'filter',
  'chevron',
  'chevron-down',
  'file',
  'folder',
  'robot',
  'cloud',
  'code',
  'codex',
  'claude',
  'anthropic',
  'opencode',
  'chatgpt',
  'openai',
  'claudeCode',
  'cursor',
  'gemini',
  'copilot',
  'mistral',
  'replit',
  'zed',
  'cline',
  'note',
  'menu',
  'pushpin',
  'pushpin-slash',
  'sun',
  'moon',
  'desktop',
  'device-mobile',
  'bell',
  'x'
] as const;

export type FolderMetadataColor = (typeof folderMetadataColorNames)[number];
export type FolderMetadataIcon = (typeof folderMetadataIconNames)[number];
